### ISSUE TITLE
Add a build pipeline instance for aicoe-aiops/categorical-encoding pushing to Quay.io

### ISSUE THREAD

**Issue by tumido** [thoth-station/jupyternb-build-pipeline#4]
Related: https://github.com/aicoe-aiops/categorical-encoding/issues/2

Hi, we need help setting up a new pipeline for building an image from analytics repo, that would package it using s2i-custom-notebook base image and push it to public Quay.io. This image can't lend on the internal registry because it's public and has to be deployable as an example for Operate First - from anywhere, including outside RH firewall.

Can you please help us with that?

**Comment by tumido** [comment]
cc @harshad16

**Comment by harshad16** [comment]
@tumido , 

if can you provide the details about the quay.io organization and repository to which image need to be build and push.
we would use the aicoe-ci pipeline , as it has the feature to support what is required for this issue.
i will send out a pull request to the categorical-encoding with updates needed.

**Comment by Shreyanand** [comment]
@tumido @harshad16 Meanwhile, should I remove the gitmodule and update the pipfile before we put it on quay?

**Comment by harshad16** [comment]
> @tumido @harshad16 Meanwhile, should I remove the gitmodule and update the pipfile before we put it on quay?

yes, +1 from my side

**Comment by tumido** [comment]
@harshad16 Ah! We can use AICoE-CI for this! :facepalm: You clever person, love it, yeah! :+1:

So, something like this in the source repo should be enough, correct?


```yaml
# .aicoe-ci.yaml
...
build:
  base-image: quay.io/thoth-station/s2i-custom-notebook
  registry: quay.io
  registry-org: <ORG>
  registry-project: categorical-encoding
  registry-secret: <SECRET>
```

I can send the PR myself tomorrow, no need to bother you with it.
